server:
    port: 8004
spring:
    application:
        name: cloud-provider-payment
    cloud:
      zookeeper:
          connect-string: localhost:2181

    datasource:
        #当前数据源操作类型
        type: com.alibaba.druid.pool.DruidDataSource
        #mysql驱动包
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/cloud2020?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
        username: root
        password: root

mybatis:
    mapperLocations: classpath:mapper/*.xml
    #所有entity别名类所在包
    type-aliases-package: com.yu.springCloud.entity
